"""Conformance test R6: Synthetic data only, generated by SimClinic. PII redaction at ingress.

Tests that only synthetic data is used and that PII is redacted at ingress.
"""

import pytest

from clinicloop.compliance.ingress import process_record
from clinicloop.compliance.redaction import redact


@pytest.mark.checklist_id("R6")
def test_pii_redaction_at_ingress() -> None:
    """R6: Synthetic data only, PII redaction at ingress."""
    # Test that ingress redacts PII from records
    record = {
        "patient_name": "John Doe",
        "email": "john.doe@example.com",
        "phone": "0412345678",
        "dob": "15121985",
        "given_name": "John",
    }

    processed = process_record(record)

    # Email should be redacted
    assert "john.doe" not in str(processed)
    assert "example.com" not in str(processed)

    # Phone should be redacted
    assert "0412345678" not in str(processed)

    # DOB should be redacted
    assert "15121985" not in str(processed)


@pytest.mark.checklist_id("R6")
def test_redaction_removes_pii() -> None:
    """R6: Redaction removes PII identifiers from text."""
    # Test email redaction
    email_text = "Contact: patient@test.com for help"
    redacted = redact(email_text)
    assert "@" not in redacted or "test.com" not in redacted

    # Test phone redaction
    phone_text = "Call 0412345678 during business hours"
    redacted = redact(phone_text)
    assert "0412345678" not in redacted

    # Test roster name redaction
    name_text = "Patient John Smith reported"
    redacted = redact(name_text)
    # If John is in roster, should be redacted
    if "John" not in redacted:
        assert "[REDACTED]" in redacted
