"""Utility to hash plaintext forbidden names and write hashes to denylist file.

This module reads forbidden names from a plaintext source (outside the repo)
and writes their hashes to src/clinicloop/naminglint/denylist_hashes.txt.

Usage:
    python -m clinicloop.naminglint.hash_names

Environment variables:
    CLINICLOOP_NAMING_DENYLIST: Path to plaintext denylist (default: $XDG_CONFIG_HOME/clinicloop/naming-denylist.txt)

The plaintext source is never committed. The orchestrator provisions it before
this issue is dispatched, at the path specified by CLINICLOOP_NAMING_DENYLIST
or the XDG_CONFIG_HOME default.
"""

import hashlib
import os
import sys
import unicodedata
from pathlib import Path


def get_plaintext_denylist_path() -> Path:
    """Get the path to the plaintext denylist.

    Returns:
        Path to the plaintext denylist file.

    Raises:
        SystemExit: If the path is not found.
    """
    # Check environment variable first
    env_path = os.getenv("CLINICLOOP_NAMING_DENYLIST")
    if env_path:
        return Path(env_path)

    # Check default XDG_CONFIG_HOME location
    xdg_config = os.getenv("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
    default_path = Path(xdg_config) / "clinicloop" / "naming-denylist.txt"

    if default_path.exists():
        return default_path

    print(
        f"error: Plaintext denylist not found at {default_path}",
        f"Set CLINICLOOP_NAMING_DENYLIST to override.",
        file=sys.stderr,
        sep="\n",
    )
    sys.exit(1)


def compute_hashes(name: str) -> set[str]:
    """Compute all n-gram hashes for a normalized name.

    Normalizes with NFKC and lowercases, then forms tokens and n-grams (1-4 tokens),
    and SHA-256 hashes each.

    Args:
        name: The name to hash.

    Returns:
        Set of 64-character lowercase hex SHA-256 hashes.
    """
    normalized = unicodedata.normalize("NFKC", name).lower()
    tokens = normalized.split()

    hashes = set()
    # Generate n-grams of length 1 to 4
    for n in range(1, min(5, len(tokens) + 1)):
        for i in range(len(tokens) - n + 1):
            ngram = " ".join(tokens[i : i + n])
            h = hashlib.sha256(ngram.encode("utf-8")).hexdigest()
            hashes.add(h)

    return hashes


def hash_names_from_file(plaintext_path: Path) -> set[str]:
    """Read plaintext names and compute their hashes.

    Args:
        plaintext_path: Path to plaintext denylist file.

    Returns:
        Set of all hashes for all names in the file.
    """
    all_hashes = set()

    try:
        content = plaintext_path.read_text()
    except (OSError, UnicodeDecodeError) as e:
        print(f"error: Failed to read {plaintext_path}: {e}", file=sys.stderr)
        sys.exit(1)

    for line in content.splitlines():
        line = line.strip()
        # Skip empty lines and comments
        if not line or line.startswith("#"):
            continue

        hashes = compute_hashes(line)
        all_hashes.update(hashes)

    return all_hashes


def main() -> None:
    """Read plaintext denylist and write hashes to tracked file."""
    plaintext_path = get_plaintext_denylist_path()

    # Compute hashes
    hashes = hash_names_from_file(plaintext_path)

    if not hashes:
        print("warning: No names found in plaintext denylist", file=sys.stderr)

    # Write hashes to tracked file
    repo_root = Path(__file__).parent.parent.parent.parent
    hash_file = repo_root / "src" / "clinicloop" / "naminglint" / "denylist_hashes.txt"

    # Write with header comment
    header = "# Hashes of forbidden names from plaintext denylist\n# Generated by: python -m clinicloop.naminglint.hash_names\n"
    hash_lines = sorted(hashes)
    content = header + "\n".join(hash_lines) + "\n"

    try:
        hash_file.write_text(content)
        print(f"Wrote {len(hash_lines)} hashes to {hash_file}")
    except (OSError, PermissionError) as e:
        print(f"error: Failed to write {hash_file}: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
